### PR TITLE
Strict comparison operations

### LINKED ISSUE #89: implicit type casting with postgres
having a field of string on a table
```
case class T[T[_]](
  field: T[String]
)
```
query:
```
db.run(T.select.filter(t.field `=` 2))
```
fails with
```
org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 205
```
when using postgres, i guess i would expect either implicit typecasting of compile error

### PR DESCRIPTION
**Pull request by NPCRUS**
fixes #89 
A small tooling to enforce compile time type equality when working with expression operations, eg:
```
Expr(true) `=` Expr(0)
```
currently compiles, even though underlying types are not comparable in a statically typed language setup.
Now when importing `import scalasql.operations.strict.StrictOperations.given` same expression will produce compiler error.

Open for comments and suggestions

### CODE REVIEW

File: scalasql/operations/src/strict/TypeEqProxy.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package scalasql.operations.strict
+
+import scalasql.core.Expr
+import scala.util.NotGiven
+
+trait TypeEqProxy[A, B]
+
+object TypeEqProxy {
+  given [A, B](using NotGiven[StrictMode]): TypeEqProxy[A, B] = new TypeEqProxy {}
```
Comment (ivan-klass) [inline scalasql/operations/src/strict/TypeEqProxy.scala]: Usually in libraries there is a private lazy val instance and such givens just reuse them with .asInstanceOf

**Comment by ivan-klass** [comment]
My personal preference would be a required import of `unsafeEq.given`, maybe it would make sense to go that way?

**Comment by NPCRUS** [comment]
> My personal preference would be a required import of `unsafeEq.given`, maybe it would make sense to go that way?

i think for backward compatibility for other users it's better to implement strictness as a feature for now. 
In order to not import it everywhere you can build your own Dialect using StrictOperations trait

File: scalasql/operations/src/strict/TypeEqProxy.scala (hunk 1 above)
Comment (NPCRUS) [reply scalasql/operations/src/strict/TypeEqProxy.scala]: good point

File: scalasql/operations/src/strict/TypeEqProxy.scala [hunk 2]
```diff
@@ -0,0 +1,13 @@
+package scalasql.operations.strict
+
+import scalasql.core.Expr
+import scala.util.NotGiven
+
+trait TypeEqProxy[A, B]
```
Comment (aboisvert) [inline scalasql/operations/src/strict/TypeEqProxy.scala]: Suggest adding at least a one-liner scaladoc along the lines of:

```scala
/** TypeEqProxy indicates that values of two given types can be compared with each other. */
```

File: scalasql/operations/src/strict/TypeEqProxy.scala [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+
+object TypeEqProxy {
+  private[strict] lazy val typeEq: TypeEqProxy[Unit, Unit] = new TypeEqProxy {}
+
+  given [A, B](using NotGiven[StrictMode]): TypeEqProxy[A, B] =
```
Comment (aboisvert) [inline scalasql/operations/src/strict/TypeEqProxy.scala]: Idea:  Is there a possibility to generate a compiler warning when this given is used (at the call site)?  It may help catch issues early and also provide a ramp to turning on strict mode in the future.

File: scalasql/operations/src/ExprOps.scala [hunk 4]
```diff
@@ -4,30 +4,43 @@ import scalasql.core.TypeMapper
 import scalasql.core.Expr
 import scalasql.core.SqlStr
 import scalasql.core.SqlStr.SqlStringSyntax
+import scalasql.operations.strict.TypeEqProxy
 
-class ExprOps(v: Expr[?]) {
+class ExprOps[A](v: Expr[A]) {
```
Comment (aboisvert) [inline scalasql/operations/src/ExprOps.scala:8]: Just to flag, the changes below seem source-level backward compatible but not binary-level backward compatible.   I don't know what the project's policy is with regards to this.  

EDIT: If we elect to go with Scala-3 (which this PR is already using), we could use `erased` parameters to avoid the binary compatibility issue.

File: scalasql/operations/src/strict/StrictMode.scala [hunk 5]
```diff
@@ -0,0 +1,3 @@
+package scalasql.operations.strict
+
+private[strict] trait StrictMode
```
Comment (aboisvert) [inline scalasql/operations/src/strict/StrictMode.scala]: Why is this private?   Also can tests by added with/without both StrictMode?

**Review by aboisvert — COMMENTED** [review]
Understanding that this is just a draft PR ... I figured I'd leave a few preemptive comments.

One general question I have is whether any of the existing Scala-standard-library `CanEqual` machinery can be reused?  Or perhaps just validating general interoperability as it seems it could be good leverage for this feature.

Naming-wise, I'd also suggest the simpler `TypeEq` naming over `TypeEqProxy` but perhaps `CanEqualSql` would be more intuitive (without conflicting with Scala's `CanEqual`)

Just thoughts ... excited to see this coming to scalasql.

**Comment by NPCRUS** [comment]
> Understanding that this is just a draft PR ... I figured I'd leave a few preemptive comments.
> 
> One general question I have is whether any of the existing Scala-standard-library `CanEqual` machinery can be reused? Or perhaps just validating general interoperability as it seems it could be good leverage for this feature.
> 
> Naming-wise, I'd also suggest the simpler `TypeEq` naming over `TypeEqProxy` but perhaps `CanEqualSql` would be more intuitive (without conflicting with Scala's `CanEqual`)
> 
> Just thoughts ... excited to see this coming to scalasql.

scala's `=:=` is reused under TypeEqProxy, but because i need to enable it in a feature-flaguesqe way and also to provide `Option[A] =:= A` and reverse equality, i cannot just directly use `=:=`

File: scalasql/operations/src/strict/TypeEqProxy.scala (hunk 3 above)
Comment (NPCRUS) [reply scalasql/operations/src/strict/TypeEqProxy.scala]: the way it's currently implemented it will throw a warning at every single usage where `TypeEqProxy` is required no matter if underlying types equal or not, which i don't think it's a good option. Otherwise to complicate this even more:
1) check for type equality and if not equal - generate compiler warning
2) but provide `TypeEqProxy` nevertheless of point 1 logic
is a bit of an overkill. imho current feature flag implementation is almost an overkill

File: scalasql/operations/src/ExprOps.scala (hunk 4 above)
Comment (NPCRUS) [reply scalasql/operations/src/ExprOps.scala:8]: scala2 deprecation pr is already merged.
regarding erased do you mean to erase TypeEqProxy like this:
```
trait TypeEqProxy[A,B] extends compiletime.Erased
```

regarding binary compatibility, i cannot say for sure, but since mima-plugin is not used in workflow and since it's _relatively new library_ i hope we don't care about it just yet

File: scalasql/operations/src/strict/StrictMode.scala (hunk 5 above)
Comment (NPCRUS) [reply scalasql/operations/src/strict/StrictMode.scala]: sorry, don't get your comment, can you elaborate?

**Comment by ivan-klass** [comment]
> i think for backward compatibility for other users it's better to implement strictness as a feature for now. 

We can provide default low-priority instance in the companion for backward compatibility, and make it deprecated suggesting an explicit imported given (will have higher implicit resolution priority)

File: scalasql/operations/src/ExprOps.scala (hunk 4 above)
Comment (aboisvert) [reply scalasql/operations/src/ExprOps.scala:8]: I believe `erased` can be applied to parameters this way:

```scala
def `=`[V](x: Expr[V])(using erased TypeEqProxy[A, V]): Expr[Boolean] = Expr { implicit ctx =>
    sql"($v = $x)"
  }
```

which would erase the additional `using` parameter list and therefore preserve binary compatibility.

File: scalasql/operations/src/strict/TypeEqProxy.scala (hunk 3 above)
Comment (NPCRUS) [reply scalasql/operations/src/strict/TypeEqProxy.scala]: i guess i implemented this idea

File: scalasql/operations/src/ExprOps.scala (hunk 4 above)
Comment (NPCRUS) [reply scalasql/operations/src/ExprOps.scala:8]: done

File: scalasql/operations/src/TypeEq.scala [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+  given [A, B](using A =:= B): TypeEq[Option[A], B] =
+    typeEq.asInstanceOf[TypeEq[Option[A], B]]
+  given [A, B](using A =:= B): TypeEq[A, Option[B]] =
+    typeEq.asInstanceOf[TypeEq[A, Option[B]]]
+
+  @deprecated(
+    "Unsafe comparison is deprecated and soon will be removed, import scalasql.operations.unsafeEq.given to surpress warnings"
+  )
+  given [A, B]: TypeEq[A, B] =
+    typeEq.asInstanceOf[TypeEq[A, B]]
```
Comment (ivan-klass) [inline scalasql/operations/src/TypeEq.scala:32]: Does it work without ambiguity? I think this better has a lower priority in resolution order, something like:
```scala
private trait DeprecatedLowPriority {
   @deprecated("...")
   given [A, B]: TypeEq[A, B] =
}

object TypeEq extends DeprecatedLowPriority {
   given [A, B](using A =:= B): TypeEq[A, B]
}

```

**Review by ivan-klass — APPROVED** [review]
