### PR TITLE
JoinNullable deserialisation fix

### LINKED ISSUE #65: on leftJoin TypeMapper for T is being applied on Option[T]
having two tables wiith relation `A.bId = B.id`
on of witch has field of custom type T and therefore provided with `TypeMapper` for this custom type. 
```scala
case class A[T[_]](id: T[Int], bId: T[Option[Int]])
object A extends Table[A]

enum Custom {
  case Foo, Bar
}
object Custom {
  given TypeMapper[Custom] = StringType.bimap(_.toString, Custom.valueOf)
}

case class B[T[_]](id: T[Int], custom: T[Custom])
object B extends Table[B]
```
having in database only records for table A, so in table B there are no records
and performing leftJoin on table B in such way:
```scala
A.select.leftJoin(B)(_.bId `=` _.id)
```
i get following error: `enum Custom has no case with name: null`
when in fact there are no records of table B and no `custom` field to perform type mapping on.

Expected result: it shouldn't try to serialize `null` into `Custom`, in fact there should be no value to serialize on at all

### PR DESCRIPTION
**Pull request by NPCRUS**
In the current implementation, JoinNullable in order to determine that R shouldBe Option or Some is deserialising whole set and then counting nulls. In cases where you have user written TypeMapper, that doesn't do nulls tricks(like inside Dialects.scala), such:
```
enum Enumeration {
 case A, B, C
}
object Enumeration {
 given TypeMapper[Enumeration] = StringType.bimap(_.toString(), Enumeration.valueOf)
}
```
then leftJoin query, where the right side can be nullable instead of returning (A, None) will fail with exception, check new test in DataTypesTests

new implementation will check first if the rest of columns are null without deserialising them into type and only if one of them is not - will try to construct

comments on everything are welcome!

fixes #65

### CODE REVIEW

**Comment by lihaoyi** [comment]
Looks reasonable to me, just run the autofix commands then we can merge this  I think

File: scalasql/core/src/Queryable.scala [hunk 1]
```diff
@@ -68,6 +68,14 @@ object Queryable {
     var nulls = 0
     var nonNulls = 0
 
+    def restAreNulls(columnsCount: Int): Boolean = {
+      val result = Range.inclusive(index + 1, index + columnsCount).map { i =>
```
Comment (aboisvert) [inline scalasql/core/src/Queryable.scala:72]: It seems you could do `forall` directly without doing `map` first, using the same predicate.

File: scalasql/core/src/Queryable.scala [hunk 2]
```diff
@@ -68,6 +68,14 @@ object Queryable {
...
+        r.getObject(i) == null
+      }.forall(identity)
+      if(result) index = index + columnsCount
```
Comment (aboisvert) [inline scalasql/core/src/Queryable.scala:75]: This mutation is a bit surprising to me inside the method since the method name isn't suggestive of mutation.  I'm wondering if it should be moved to the call site instead.

File: scalasql/test/src/datatypes/DataTypesTests.scala [hunk 3]
```diff
@@ -212,5 +212,25 @@ trait DataTypesTests extends ScalaSqlSuite {
...
+      "???",
+      Text {
+        case class A[T[_]](id: T[Int], bId: T[Option[Int]])
+        object A extends Table[A]
+
+        object Custom extends Enumeration {
+          val Foo, Bar = Value
+
+          implicit def make: String => Value = withName
+          // implicit val mapper: TypeMapper[Custom.Value] = StringType.bimap(_.toString, Custom.withName)
```
Comment (aboisvert) [inline scalasql/test/src/datatypes/DataTypesTests.scala:225]: Remove commented code?

File: scalasql/test/src/datatypes/DataTypesTests.scala [hunk 4]
```diff
@@ -212,5 +212,25 @@ trait DataTypesTests extends ScalaSqlSuite {
...
+        }
+
+        case class B[T[_]](id: T[Int], custom: T[Custom.Value])
+        object B extends Table[B]
+        db.run(A.insert.columns(_.id := 1, _.bId := None))
+        val result = db.run(A.select.leftJoin(B)(_.id === _.id).single)
```
Comment (aboisvert) [inline scalasql/test/src/datatypes/DataTypesTests.scala:231]: Should there be an assertion (or two) about the `B` field values as well?  (`b.id` and `b.custom`)

Comment (NPCRUS) [reply scalasql/test/src/datatypes/DataTypesTests.scala:231]: B suppose to be None in this case, since it's left joined, I'm not sure what do you want to assert extra here

File: scalasql/core/src/Queryable.scala (hunk 2 above)
Comment (NPCRUS) [reply scalasql/core/src/Queryable.scala]: good idea

**Comment by NPCRUS** [comment]
@lihaoyi ping

**Comment by lihaoyi** [comment]
Thanks! Feel free to ping me when you're done with your PRs and I can cut a stable version for you to depend on
